apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-selector
  name: nginx-selector
spec:
  containers:
  - image: nginx
    name: nginx-selector
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    gpu: "false"
status: {}
